apiVersion: v1
kind: Secret
metadata:
    name: libation-sync-ssh
    namespace: media
type: Opaque
data:
    id_ed25519: ENC[AES256_GCM,data:YXyaIGafYnAYI/0NhDNejpHKO9zkHMsRSRY+v6unAnkrz6mo+Z+XVlPlmWo1AAHmvHsY2CJSlHE5L3+d52k72l8HMqHbWG3PogDgAQdIT2dK8UPu7uautI3XqKLbHkwZOoN1z97k1RJIrQYN0OR4u3jlekO/TLTyv92qrOmHeqMLxt298oLVUs5Wn7ocSOlk8Dz8CEYNL+mXxKepH+7m32GFEmIjRby/0PHFqkam8JRtPc9ku+BbZpEURDzR7NKZKCdDk7pDRztEI3UQHZpbT7j7XbxyH5rPRe7hJBqvlJqwWZZzCb0zPPsH4w+3jHW56LxkRUmG3jMaU7BYTSTG2k7r0DGzycHHlgUtuyzTf8/qlSEDIxqhDFJFGGWRcufGCShtOUCYPX+seLbEqnNElFp10kMKifRly36FMb82tdHbplJszmGYDzvFxptTBihOfe4jv+gJWUKIP2AqEQK8o6P3B+9rUBXfZOkrGI6E7f74+xp60RMTmCw0cjlVjfHxzPr9p6ZD8GQu82UFy6As5B9qFhxAuwYjTKpwOCXlqzs6VW3gODH/vfODF3GXlOdDI5AxfGJryhi3Vm1p+En0Axz39HG/2nEt/okD1N+xP8/qzkX1lgebhb0TP/Kp3A5t6vFPWYizeRqXJxb9IGn1ikj+5RYUfRX/h4p2So2P/yMb39z98OGLcW4/ghTWgJB4bA+b3Hf/a2Rc94bRl3f0OdWbfL9aXWnQL1ByqVoPQ1udikGUQACSmG51355gmNIu,iv:Awv04MkQHvF2B/Y2VmdbPpWc0yXY+SR3IvnTNG4+8uc=,tag:1V+8x/t37TS6R0llViZJBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1508vrpede8x0lspk6grkr4qlc44j3jzr4ehcddawlqlt7s65spgsaaacg7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRWo3VnBxNGNzTXp2M1Az
            OUZseW5zWFFQRGZDTi82UGxRQUZwMmxWMjI0CjBEa3VpUE9ReVVleE1BWGR2RDB6
            K283TVZXT3h6QVUvSXZ3VW9yeWkwMFEKLS0tIGsvOXRaV0IvcWdMekRaMU5GNCtK
            V2dXUFpCamtjajNZVFhkN0h6Ykp4TmcK6V40hKVqefV6YOnR1f6sefI2hqJVU8Hd
            IRDvzZbcF43hb+9mN+xcT2ECCmpfFXTo7qZfT9eGULhhTkikJLG5/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-02T16:39:40Z"
    mac: ENC[AES256_GCM,data:tL67su5eOPZG5hHYdAyI+dPFS0j8pIGeVKqb0ZizyBfzVeK+Ty+VVuwTqF52req5N0UXJeARXeVH41IXUD5AUMFem9+odJTx08LDQmijhhnuW1fmgJW8wS9AtF1cum/YUrWd7dRlynGgjOTlus6c5b/yDoDutyPQbf9v9w1+KUA=,iv:H5dxp70JKdDlj1uDJ7j71NFfbRpN+Kp/1I1pqMS7TBQ=,tag:5bhD6zgA32L+BAPgOPHmnw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
