apiVersion: v1
kind: Secret
metadata:
    name: libation-sync-ssh
    namespace: media
type: Opaque
stringData:
    id_ed25519: ENC[AES256_GCM,data:ei6OoZnAVaSuCUJHvcwPlhJtB5J5zLKwi4lfKN97oluCWFjCsQ8LD2FgIPtcTvfo3byoAHem+PN8OxfkHIiKhR3RUeYyrISTLvzaYRKQ2bBZE2U5eAUxXvcu4sBqBq+oSeB2uo3Ei8BV3Yxmx/4Wp71htVLR3FEesP2zSQlgyCEK4JlHcExvJ9/tH/RE5ZaE/F0w5b8aBnjPS/fZhsSJ2q3WCeQ93HtupI/6rq0w30XqdpEXjsnw2fuyE8yUZHoUT6sqz29cjPhzv8W77c1BQtnCLo/COnim7jUOhlXSN1miLK3EUUoIY4G+uXv7Lf/qRALIyvdfeZEVt0xrPO6wIDOnqArNZC4oMYH4zkiX1NPyc5QfCXnDr5DiJeo76MrqCeYNVT3kFqYAcSpcTJQkQihVMoWhx7bH6ICi1Q7LYIXgKKHK7GDh+DaPyU/1u8fI0CC2nXz1ACl++y2ilKQMU3bkTZllmRZnoX07YNxkcjcUYVEqb0AvcDUC8yUSqqpWTfktNoEgVOI/w9I4SOHleVHqSKm/vd9YqOcmFXEV1TTbrs/xZKZ+O4xqGp7/fuE=,iv:SOLmmPBOJHzm+xM2ZGuVoKf7Vr2hPrIOmtBN4W6lpAk=,tag:5i113nNQMzmq1UKOt6eNww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1508vrpede8x0lspk6grkr4qlc44j3jzr4ehcddawlqlt7s65spgsaaacg7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQc25LS3FNY0hFdmJjWUQ1
            WWYvOFRNVWNJSzcrNFE2WGNmd2tkT3hTcUg4CmFHSTZGcEM4cWFKRTQrdWNCczRZ
            bnZwZWlxRWZXdzFQMHkxRjdHQXBBZzgKLS0tIGltRU8xZmhYTWx5TUdFRWdhck9W
            UEhVaHpFMW9zMEsvbDNFWU1KQ2Y0VmMKwDJFyaSmTqV99QldWV9E8PbyRQAVIA9e
            ZyN3wWOTLEiOeXByaxF+qjkmliWdWsrZUbo4d6MiO2zg7X+NXt7NwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-02T16:33:24Z"
    mac: ENC[AES256_GCM,data:ueSqeXc73CMMRZOSKlGTjC+FXIVzG5/9kuVb5kjkR9oepQsfg2WEuAxqm60ltPfB6Aax/J1e24i6YRvQFtberILbP07Qlsv/KYEVsRsSQZZOgaf+T+1LGp4kgRnePVIhG017CWsK7g+JTR3KNtxIQFF9cwDcmB7rZAbqgI97RIU=,iv:caC6rmwI1b2P2aLVGalsELwUVkZ0PQOeESCl+EuLXvc=,tag:0OY7fH66pvLzIQ1KhZjChA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
