---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tautulli
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tautulli-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/name: tautulli
  data:
    - secretKey: TAUTULLI__API_KEY
      remoteRef:
        key: tautulli
        property: API_KEY