---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mosquitto-auth
  namespace: home-automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mosquitto-auth
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .mqtt_username }}"
        password: "{{ .mqtt_password }}"
  data:
    - secretKey: mqtt_username
      remoteRef:
        key: mosquitto home automation
        property: MQTT_USERNAME
    - secretKey: mqtt_password
      remoteRef:
        key: mosquitto home automation
        property: MQTT_PASSWORD
