---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mosquitto-auth
  namespace: home-automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mosquitto-auth
    creationPolicy: Owner
  data:
    - secretKey: passwd
      remoteRef:
        key: mosquitto home automation
        property: MQTT_PASSWD
