---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mosquitto-auth
  namespace: home-automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mosquitto-auth
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        passwd: |
          telemetry:{{ .mqtt_password_hash }}
  data:
    - secretKey: mqtt_password_hash
      remoteRef:
        key: mosquitto home automation
        property: MQTT_PASSWD
