apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:s8HdC9Vrl+sZtBecSfKiXpt+sAGdtaj8f11+a6fJRGBd/2wX,iv:cC4TySFfDr/hfyil5g84pG4X/vYyjJDccdUgk06pLlY=,tag:cW8jWHIPMnQAwRbwc7SMzA==,type:str]
    credentials.json: ENC[AES256_GCM,data:N+MujW5vOsW/+YxnUDtMUmxxJkXM8HIoZ1TzLD5FYt0oRe1i4oo7dj7Q1mBAXgtCqJAPL2oNxtQqusk0pB0CtBwMh/8oDUCrZGPxBDRoIREHOSsPFBO8EZA1Vh5gV5D8FAY9HQo6kR+myMuiaqevtCUXgtaw1nTAYgWma5EtKY8x5V5hJSYJxiSq+O6puFEb5WeUm3nrX+1IF/b1Yeybky4i3nlHNz0MkGm8ySpmdw==,iv:/d93u7WxcwXAievjXVnQMCzHbz2IOY41DJgXJwCgc5U=,tag:GgtMS0d/ueQp2hY6eK30Sg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1508vrpede8x0lspk6grkr4qlc44j3jzr4ehcddawlqlt7s65spgsaaacg7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMnJCaTR6SkNua0ZlckNH
            M21ZSWN4eXVFSkphNmpnNEJjaVduZjBXMUVvCkNJSjEvMDhUYWdqUVRJMmYwc0Mx
            NVZRTDJWVkE1SmttM2dpZndmNVdQUDQKLS0tIFB2c1dFUkxhTnFzbHlDalMzT1Fj
            d3ZtVzB3R0RSWmlYOVBQSmZzekRsWmMKQU7LSLp9rhFDU5LwGrDItUjKf40A1LZf
            0rh9Gw3mNwjmEt28Wmo/WK12HaVzZ5Y8iM9gLU90J9SAZyVsxoM4nQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-15T00:30:05Z"
    mac: ENC[AES256_GCM,data:uqwoloXpoYHfn7BiekQjZcBkzp5VvhqE+GDKIkHDDn25Nmvl2O3P2sfmfS9Zg9UvBJpsN8zwMinO5qMZeOpa/2QDzoQ2+DOkT55d9Ki2tGG28IPcPsQcqYOY5btIRk4+Jj7VY764sYHYEIfTaB5hcA6NIvhlbQiHgBJkdQfKc/Y=,iv:3q4W0DpTUZhnYHBsj+TgsY+33TBgLg3u4+8N84DJStY=,tag:MeQ0/nZEp4VbkbJq6q6JiQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
