apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:FZ01NAp6qce7Bh4VIkbxI8HRaYgTT92NNoX+p6JsEpgEVFEW,iv:ezSx8mxMgP0M6Zwlr6yZfc4YIqneXhpCAaRTBFm8A90=,tag:tEPe42viTxa+FlKptKaNDg==,type:str]
    credentials.json: ENC[AES256_GCM,data:5SwmzlnHOT50acGAtiVzMEBTZpY0G7BgZUiYbHyes15zSlCzY3QU2V1J298CaXDZV6GqSkneCeAqkSBUobcGuPM++lKAMMIT4zFq9jY0I9NbX83wu/XplmwUoSwDQ5KEIPKUrMZwShZZKHFQN+uzXKJVNjxPweCkNQZXVJSIi/YjnB/Sjj5+kttePY4SH8EPu4gEY4yQtudm5IzRSkqQDYd6wvy/6xv2Bxxx/IRMhw==,iv:+uf1rMhZtDeIQtcM9YbhplCeecw64jSHgU0D56t/DXo=,tag:tkub00Qunjy5CIs9ryef2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1508vrpede8x0lspk6grkr4qlc44j3jzr4ehcddawlqlt7s65spgsaaacg7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbXNZQjBmNEJEay9OOGFL
            QzE0TnZRTHlPeHVhcnNTWDVySmN1Z09GNGkwCjVKWnptME1Db1RPL1p1SENXcFhk
            cGRFMkx4UnZ3aGxndUxQNHpXZ2F5cEUKLS0tIFRkSTIwU0ozQi8xNUtGaDdNdExF
            TEQ4NU82UjRmdHdHQmw2amc2V0pxcjgKTOy0xC8JmseApla2AJisRwdBqFPNo2EN
            6RPa752GzhAvTlSLZm8dFCYc2rxQ4BE2f+XhhUkZbNTSJwzhFto4Wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-19T18:28:27Z"
    mac: ENC[AES256_GCM,data:aqiBuFqh24I8hrXdwt9Qkgc465gtQBI9lN9GmlbmHU6Hh+Scjzy3beCMtxbkyQOlTUwvYDHaATI/POtdOeZ2wnNI7YgkHEg3x6CMCrNQaTgcNyFndeJAt8FPED8hFP7+KQdvzo66VgyadJTQJqL+2Fx+RIPL7MuPApgMxYqcnvI=,iv:Ehk+1Zm2hjxSFiQLRZgOE2Cn8lcdEA4/cYGctXUL79s=,tag:EMlzIZ/QbI8ZUh1sdzkTQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
