---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./gatus.yaml
  - ./helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: teslamate
      app.kubernetes.io/instance: teslamate
