---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mullvad-wireguard
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mullvad-wireguard-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/name: qbittorrent
  data:
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: mullvad vpn
        property: wireguard_private_key
