tap "fluxcd/tap", trusted: true
tap "go-task/tap", trusted: true
tap "siderolabs/talos", trusted: true
brew "age"
brew "cloudflared"
brew "direnv"
brew "fluxcd/tap/flux", trusted: true
brew "go-task/tap/go-task", trusted: true
brew "helm"
brew "jq"
brew "kubeconform"
brew "kubernetes-cli"
brew "kustomize"
brew "moreutils"
brew "sops"
brew "stern"
brew "talhelper"
brew "talosctl"
brew "yq"
