apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cruise-caller-admin-secret
    namespace: selfhosted
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:n4j+9uM5y9uGvc9NYM41Bws+ECpBNZjUujOkqzrzFxzyTGmigAATbRc+T8zZzKkd,iv:xdX6qpNFVAK21QNqfxQv6RpqlX4zfmqGGJRHq6ooFJg=,tag:miD+N+mHsxxc6zaKoTgTbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1508vrpede8x0lspk6grkr4qlc44j3jzr4ehcddawlqlt7s65spgsaaacg7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYlZlV3ZuWGNzMWVsMTRr
            ZDZGSUgzZ2IyQWZaU0dveEJ0TjZZY2Rzc0g0ClF2a1c5cmFoQy9pL2h5K3k2ZnVu
            NUpqUjJtZVpsaWMyTE00OWdKUitBNUkKLS0tIDJpbHBZT3pNR0lMbjdmam5qaXJ0
            TnNpVnpmWXY5NUhNTjc3ZlNIczNEUXMKDXl6f2q371Fb73gZE0zWm7JfQ9/3/9BP
            rbigJjQLJzcYRUQnEBFYsdOKmqy78xuKC42lqfPqDq6OIPDbsrWK2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-07T22:59:50Z"
    mac: ENC[AES256_GCM,data:qjQd+lnpFs2MHslbPMD4XmSbPPkXi/Wr2F8ZiWxT4W1FtwWWSKipdURySgKEqYTvh9wQw19OIjCmd6p/ZjxAwFCRQy7ZCvNUM4kwI/flaD4h3+9NP3Re1ApY17shyGaRMX0HWsK8WbCDK+lFbflZ1kCdBqHE/lMxGbqARi2+UxY=,iv:oroT2fFfeCzNnG07MJ62rtlFsF8khSZjDC/UOE+Oo30=,tag:H6WN5Z5qbTxbPvqZKK+i5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
