---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cruise-caller-openai
  namespace: selfhosted
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cruise-caller-openai-secret
    creationPolicy: Owner
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: openai-key
        property: OPENAI_API_KEY
