---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cruise-caller-data
  namespace: selfhosted
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: iscsi-csi
  resources:
    requests:
      storage: 1Gi
