---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 5.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/bazarr
              tag: 1.5.3@sha256:4689534b3f49917ebad9371ad376f6659236c690eb862e72ba43d349c4b5dff6
            env:
              TZ: America/Denver
              PUID: "568"
              PGID: "568"
            ports:
              - name: http
                containerPort: &port 6767
            resources:
              requests:
                cpu: 25m
                memory: 128Mi
              limits:
                memory: 512Mi
        pod:
          automountServiceAccountToken: false
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        controller: main
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        className: internal
        hosts:
          - host: &host "bazarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts: [*host]
    persistence:
      config:
        type: persistentVolumeClaim
        storageClass: iscsi-csi
        accessMode: ReadWriteOnce
        size: 2Gi
        globalMounts:
          - path: /config
      media:
        type: nfs
        server: ${SECRET_NFS_SERVER}
        path: ${SECRET_NFS_PATH}/pms/media
        globalMounts:
          - path: /media
