apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:c7kgMrF2BQ0v7503X7hMLD6kv3WuKgIL7Z2a1e6hB1+s32wHXBsrLNgYB2NbtUlLSz0ZkWHak96FZOfFnB8bFoC3RbLqNQ4pTRcmayW3BurRdO+JgxNY+zlkwMJ1rA==,iv:ox5NtXXLC3dVK5Qjb5FhYg9JPB2qccxA6USB+3R8wlo=,tag:H6dlydnBkcr2ZOjxXCBC7Q==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:+xBLipyhxsva9Xv4WuU=,iv:5OJn2gUwIOgIW26HW0UQcVGyKzNrgLBSYNSSuxfBEU8=,tag:lalFFNXpI7GxoEjURF2DYA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:AH/BKlEckhVsN8QmdzngzDtZoAA=,iv:tf7369TWIy/u64iVgqIoBFouezwJmkwkx6s2rNqoMRY=,tag:RD4QAJ6DuaItod7YNKVQbw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:W27Pl+xuPduncc5fK1eBAZMrD5Tq6S/5Eka+g9UlbiPaL0Zt,iv:t/s0jLIJYd4H545SoKbVKc3IEGcQnOuxlHGYl30qYx0=,tag:Y7fZLssu+M35ktx+mgMO+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1508vrpede8x0lspk6grkr4qlc44j3jzr4ehcddawlqlt7s65spgsaaacg7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5T1JyZEVxLzVYU1QvVjdn
            TVA3UjUzWHU0dG0zd205R0RsRFN2M0tnUWxVCm9wcS81YW9Ndk1pMDd2eWhjZDAz
            Skw4N0dLelJvTVI1K0ZJU2JlY25BNXMKLS0tIDZHWmlEME1MRDNrRjFSaldVTlhV
            d3kvc2IzNk9IelBTMlZWcW0ycjdDNEUKUgqsEsqEdXFmeOYRWCdNcLVaZ5ZpoMPv
            0RA/6kGpR8uurw7CVio6enksWLAfgXf8jCwL2VtsgzKONQ8f2ExrRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-14T21:11:50Z"
    mac: ENC[AES256_GCM,data:xXEXa9vURhQxGOtl1qvD1tjJ6q8Md3LwK1GWz0NwbnO7GddSUA4H/YI+AK8rYzxrNpSsSqgPIKuoIkrxI8sbXucYLpQ9RGM507VgcSg8QwI8GSYnrOW8QIUPqacRQchzgC+CupjLo7IuI12V2HOPymbojG7Mi+XF9Zw3x60fLV4=,iv:ckcPjlL3e7OoVfv01psJGSuxFyINotzN/7xOUD3XP38=,tag:AEQi0AuQe4hK8h2/ga7LTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
