apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:Mn1l9091qIRftPlPGMPc/PIZeYmfnFjjoXxxZ7uEYIS2mFo/2gXArbWNtfFV0Qil9cu+OlymAzj9WY75dZklsxCENFqC57JpbUiYh7bDfQP5NPepHMFobaV8g18s1w==,iv:mB7k1m5OcfZCxnEXxRkGWkD/o+vu9p1JaXlp1EwCjgA=,tag:hAcYkP/Qjf4shoZGuVJKiw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:aKSVpXoJJWAlcakGrDI=,iv:WJBtSNokTshOpnBW1I6viToBlh8Cu18VBC1bGJPLW8I=,tag:4xVBMXf0mqndmVy0+IgXEA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:LZBMS5GN9/KXjuA2eW+OhQcsEIs=,iv:R0JzR3UH9QKBnBjmqdJHim5MWmlR1YmDfIJ0oa+z7+A=,tag:3J2wrsB6U6qyUT/hXgbmvw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:C+6Hq19lxduoOdZAAs5HR2D9R83trq/5/AsrStIRwW8P9oSz,iv:mal0lUJoATYJ777F+BBjseQElhHojszM+RqisLHxy4k=,tag:V6bx9DU2F83mxk44VKZOWg==,type:str]
    SECRET_RANCHER_ADMIN_PASSWORD: ENC[AES256_GCM,data:N4tBiT+9mnt9bw==,iv:cMxXl6rg5fBjq/YPNKlVHIu0sCXHfQJDxgMi3sqq7wc=,tag:ickTo6ucB98hd8jEcd5jLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1508vrpede8x0lspk6grkr4qlc44j3jzr4ehcddawlqlt7s65spgsaaacg7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvL1NvK0syWk9TazBoYVF1
            aDRrN3FRSVNWeEZhajA5MVMrZEpSN292OFJrCnFSTzJYNTVmelYyNnV0amcrdkV1
            NWE0Tk5FZmtja1UvR0U5cHhKMTNJQUkKLS0tIHZMcWJuNW9BMjhkZXJxQW1Fand1
            Tm9Pd2JsekxKaklqSFR5QnluclVCelUKPsGp9bPhUzQ7Zte9adb9Xe01QOCyRdjF
            T5r3KTKSSCYTz5VPNw/HWq4YJvVfjJK2qG05ONg+oQHvHfRy/Q9kxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-19T18:29:38Z"
    mac: ENC[AES256_GCM,data:g11aRKP4rdsNvFGnt5qmwlcaEGnfTFVdGRK/gIsbo17ded6u+/ttt5mjrkuiT1m/32GBGu9PRe9/MO9L4LddZu95Edo2QtTZJFFcrnli4QQ2g7xgfWd3PVCB2z18pwsm7SPBct3zXFSD6m+K5OEJWX+HTLK2CzwHxLFKCDEuH24=,iv:TxOfdqGzfodIJ+MhsuKtT9kctf9rGtMqa0OYNBbwLwM=,tag:P8fh7A04hi+cf2SpRHq1Cg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
