apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:7Xtd4JyXsdLqiSI81S/XyTpCx8s3fBC/o16B5RF/odE8Gk1EyaNqxniKmg9CYH6nQQtQvoNcxgzC3Rr0kdDN3RsORZn2b2BRYJWpp7nsWcnaBGmdB19lqyOo3pTxpQ==,iv:lB+bZnNNfzHrSCr2A3vD7FnffwSpB488Cx+khKYxHQc=,tag:9Ib1ev7buR3HeQxUafDb1Q==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:zT7fa3GKUAgywwG/ANQ=,iv:TzFlwIRvghKWX7DDR9c57yw/FaAvcQtpEUXEVPt0sHs=,tag:2T2L6GFqW4aKKzAi5S7uyg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:SH/tlZUwqADEdw4dY5IZEfkHJb0=,iv:mdtI+Z7H2Jn0Pz2Xahnjt8Opu3UREPByf/mtci990Rc=,tag:gRJ8PC5K4I2sSOU7YSUsaw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:yd9qVMHX350kfzM4cwL6Hsv4gOat8pv5ADtx8DoZfuXw9/XF,iv:Df3t5W7VvcK8qMSGiJU/T1ec3HGqH7qgSfWutGpufOE=,tag:n4mfzYeg8rraDtTtVv74sw==,type:str]
    SECRET_RANCHER_ADMIN_PASSWORD: admin12345
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1508vrpede8x0lspk6grkr4qlc44j3jzr4ehcddawlqlt7s65spgsaaacg7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFaGNIcHBWWC8vRGI4V1F6
            dVdVSTBjaVl2cU9zdkUwNnljN29kb0NPRVdNCnBFNVVvNHRIazJ1dUFtb1FSN1hr
            TkEvUDA3N2R4VDlhWkhtQ3loMGVWUVkKLS0tIDlTdmc5ZEp1R1JHOVQ1Y0htc0tT
            WVhzTWIwN3QveVRsVTJwK1paaFRyOTQKowmMt4w30PK8nBniSYD+vjsWXWrrw8Bq
            Pvb1MgfBBgKKA7UI4PaIhSYECzsFhvWkETr/vuEYvzXDm5qpbptCDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-15T00:30:05Z"
    mac: ENC[AES256_GCM,data:wgVGX7qeMBKaBRz/XNT/q9KRn9kx4ng4uddT0IlHFT+b2qfCvbOheYuWbXKV2iE+3IwYIGCB8H4wmnPw5gmRPieDAM7tJ0kfphkRW/zgXceYdjnjvdFoQVqzdkOZN02ouIbBsuZkNqvk/Uz5Z3HFe4XGt6kjUGJxBHWODZT6dYA=,iv:3xiSMzLq/e5bK7bvakH9LL0hLFZJhLct0i37a+MmpTo=,tag:8FesPneEFk0CvhxTKR0cTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
