---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  # dependsOn:
  #   - name: intel-device-plugin-gpu
  #     namespace: kube-system
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/home-operations/plex
              tag: 1.41.6.9685@sha256:37d36646471fb905a0080daaaa1f09ad3370b06149ed5f94dad73ead591cad0e
            env:
              # See https://support.plex.tv/articles/201105343-advanced-hidden-server-settings/
              TZ: America/Denver
              ADVERTISE_IP: "https://plex.${SECRET_DOMAIN},http://10.0.0.233:32400"
              ALLOWED_NETWORKS: "10.0.0.0/24"
              HOSTNAME: plex.${SECRET_DOMAIN}
            # resources:
            #   requests:
            #     gpu.intel.com/i915: 1
            #     cpu: 100m
            #     memory: 2Gi
            #   limits:
            #     gpu.intel.com/i915: 1
            #     memory: 10Gi
        pod:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - "k8s-1"
          # nodeSelector:
          #   intel.feature.node.kubernetes.io/gpu: "true"
          #   kubernetes.io/hostname: "nuc11"
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups: [44, 105, 1000, 10000]
          # securityContext:
          #   privileged: true
        # statefulset:
        #   volumeClaimTemplates:
        #     - name: config
        #       accessMode: ReadWriteOnce
        #       size: 100Gi
        #       storageClass: longhorn
        #       globalMounts:
        #         - path: /config
    service:
      main:
        controller: main
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        # annotations:
          # io.cilium/lb-ipam-ips: "10.0.0.233"
        ports:
          http:
            port: 32400
    # service:
    #   main:
    #     type: LoadBalancer
    #     externalTrafficPolicy: Cluster
    #     annotations:
    #       io.cilium/lb-ipam-ips: 192.168.2.200
    #     ports:
    #       http:
    #         port: 32400
    #       # GDM Network discovery
    #       # https://support.plex.tv/articles/200430283-network/
    #       gdm-1-udp:
    #         enabled: true
    #         port: 32410
    #         protocol: UDP
    #       gdm-2-udp:
    #         enabled: true
    #         port: 32412
    #         protocol: UDP
    #       gdm-3-udp:
    #         enabled: true
    #         port: 32413
    #         protocol: UDP
    #       gdm-4-udp:
    #         enabled: true
    #         port: 32414
    #         protocol: UDP
    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "plex.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: plex-pvc
        globalMounts:
          - path: /config
      tmp:
        type: emptyDir
      transcode:
        type: emptyDir
      media:
        type: nfs
        server: ${SECRET_NFS_SERVER}
        path: ${SECRET_NFS_PATH}/pms/media
        globalMounts:
          - path: /media

