---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vrm-mqtt-bridge-init-db
  namespace: home-automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: vrm-mqtt-bridge-init-db
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: INIT_POSTGRES_HOST
      remoteRef:
        key: cloudnative-pg
        property: POSTGRES_SERVER
    - secretKey: INIT_POSTGRES_DBNAME
      remoteRef:
        key: lakemates victron integration - tranquility
        property: DATABASE_NAME
    - secretKey: INIT_POSTGRES_SUPER_PASS
      remoteRef:
        key: cloudnative-pg
        property: POSTGRES_SUPER_PASS
    - secretKey: INIT_POSTGRES_USER
      remoteRef:
        key: lakemates victron integration - tranquility
        property: DATABASE_USER
    - secretKey: INIT_POSTGRES_PASS
      remoteRef:
        key: lakemates victron integration - tranquility
        property: DATABASE_PASS
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vrm-mqtt-bridge
  namespace: home-automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: vrm-mqtt-bridge-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: VRM_EMAIL
      remoteRef:
        key: lakemates victron integration - tranquility
        property: VRM_EMAIL
    - secretKey: VRM_TOKEN
      remoteRef:
        key: lakemates victron integration - tranquility
        property: VRM_TOKEN
    - secretKey: VRM_PORTAL_ID
      remoteRef:
        key: lakemates victron integration - tranquility
        property: VRM_PORTAL_ID
    - secretKey: DATABASE_HOST
      remoteRef:
        key: cloudnative-pg
        property: POSTGRES_SERVER
    - secretKey: DATABASE_NAME
      remoteRef:
        key: lakemates victron integration - tranquility
        property: DATABASE_NAME
    - secretKey: DATABASE_USER
      remoteRef:
        key: lakemates victron integration - tranquility
        property: DATABASE_USER
    - secretKey: DATABASE_PASS
      remoteRef:
        key: lakemates victron integration - tranquility
        property: DATABASE_PASS
    - secretKey: LAKEMATES_PUSH_URL
      remoteRef:
        key: lakemates victron integration - tranquility
        property: LAKEMATES_PUSH_URL
    - secretKey: LAKEMATES_SITE_KEY
      remoteRef:
        key: lakemates victron integration - tranquility
        property: LAKEMATES_SITE_KEY
