---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vrm-mqtt-bridge-init-db
  namespace: home-automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: vrm-mqtt-bridge-init-db
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: INIT_POSTGRES_HOST
      remoteRef:
        key: cloudnative-pg
        property: POSTGRES_SERVER
    - secretKey: INIT_POSTGRES_DBNAME
      remoteRef:
        key: lakemates victron stage shared
        property: DATABASE_NAME
    - secretKey: INIT_POSTGRES_SUPER_PASS
      remoteRef:
        key: cloudnative-pg
        property: POSTGRES_SUPER_PASS
    - secretKey: INIT_POSTGRES_USER
      remoteRef:
        key: lakemates victron stage shared
        property: DATABASE_USER
    - secretKey: INIT_POSTGRES_PASS
      remoteRef:
        key: lakemates victron stage shared
        property: DATABASE_PASS
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vrm-mqtt-bridge
  namespace: home-automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: vrm-mqtt-bridge-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        DATABASE_HOST: "{{ .database_host }}"
        DATABASE_NAME: "{{ .database_name }}"
        DATABASE_USER: "{{ .database_user }}"
        DATABASE_PASS: "{{ .database_pass }}"
        LOCAL_MQTT_USERNAME: "{{ .local_mqtt_username }}"
        LOCAL_MQTT_PASSWORD: "{{ .local_mqtt_password }}"
  data:
    - secretKey: database_host
      remoteRef:
        key: cloudnative-pg
        property: POSTGRES_SERVER
    - secretKey: database_name
      remoteRef:
        key: lakemates victron stage shared
        property: DATABASE_NAME
    - secretKey: database_user
      remoteRef:
        key: lakemates victron stage shared
        property: DATABASE_USER
    - secretKey: database_pass
      remoteRef:
        key: lakemates victron stage shared
        property: DATABASE_PASS
    - secretKey: local_mqtt_username
      remoteRef:
        key: mosquitto home automation
        property: MQTT_USERNAME
    - secretKey: local_mqtt_password
      remoteRef:
        key: mosquitto home automation
        property: MQTT_PASSWD
