---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./configmap.yaml
configMapGenerator:
  - name: vrm-mqtt-bridge-certs
    files:
      - ./configs/venus-ca.crt
generatorOptions:
  disableNameSuffixHash: true
