---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: db
resources:
  - ./cluster.yaml
  - ./gatus.yaml
  - ./scheduledbackup.yaml  # Enable scheduled backups for regular full backups
  # - ./prometheusrule.yaml
  - ./service.yaml
