apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:DJmIOS3P4TXXQPBvGBXbw9ejMvIjWKMBQfnL0op85ZQ=,iv:9Aq2meXeKl0F4BvfohZAbAuNBdLIKSSiHhXP1SzqOaA=,tag:7pQNTANjynpD13x+GNr47w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1508vrpede8x0lspk6grkr4qlc44j3jzr4ehcddawlqlt7s65spgsaaacg7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBha0VNRWdWYXpkL0F3WE9j
            dXFjbVFnMHhSVjhQbFNkajRqYzZDZ3RyMnhRCmJ3M3pvUjFTVklFZ1pVcHFSZndn
            Slk0OERCV3JXRGQ3NUFOT0ZxYnN1a1kKLS0tIFY3Y3JhUzhDL0RpZ2drYldSYUJP
            Y2dLdloyQ2F5bkF0SVdXdS8waXg2SWcK8duTY57DE9bcV/3BJbw/wZMsjsD91RrH
            Ncj5DuqOFnV58kcf1HeYoBv2yPm+9xGUgwxRWpW6s/lNp17mgDugvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-14T21:57:18Z"
    mac: ENC[AES256_GCM,data:Em8Cu2BUmRcZahsbphskXDgMsZqAaigGt7GEix7k3IhAlAo3uZwFL6CpgCq2zWJG0SesWB87yzX4Got7iV657PvW7FZXhQ0CzCo47TJxMwDM4P4QipwxT5Pt9pCMd33WdImfw7Ec479YHAPCEwDIGBxA1crctbPpQqhNo7O0Hn4=,iv:1cQQ9Uc3IleggZXZhfEcQfOazsvkMzWesaStY0/JmyY=,tag:gEDK0mI6XDk3pmzIpHP1dw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
