apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:+S5Rnm5aO3/noZ27q4/+ZIrxxxwRXSVJuqElChTziLg=,iv:CA714yYnr9619EVuFnih0fDh2xdAGRhlCLvCfYaltLk=,tag:9cXNIBMqyDESJhHsGzrw6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1508vrpede8x0lspk6grkr4qlc44j3jzr4ehcddawlqlt7s65spgsaaacg7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYYTFsaEhHejZ2Qjh6QXpy
            cEdyMXBmSFhkbHZFYk51cGhUZ2hxa1ZtMUhRCmhhczZ6dkhzdW1ISE44Ty9wbzhx
            UDM4NWw3eWRYbjVTSTJHVkF1a29aaXMKLS0tIEFsSDVrV2tOalVzOE1DMzgrOHdo
            VDdRQnZZYjFCNkRRcmZtc20vVWJoV2cK+Gzn+Uk9q1vHKPBlkuGKN1dtaKAwZb9t
            4C3Gwm9Hl8f9D80tsUkaHCVU6YW+E7hRH0lelQVWiz6Ggzj+eTlLAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-19T18:28:27Z"
    mac: ENC[AES256_GCM,data:jJZYkqJ/+PkDFfC5CKL3+mBJtTJLhI0qZszKbIFRQv/W9ZEo3Qg0+r49gYWHrpCD2QcxkDkQ6YIjw0aD/tfdQyFi3veS0nQm2YHXDwwS7StLoeRJ2xvAYOn+pgoTbDVvqrxcuxhUyxrF/265Ly1HfzDl/CrziuccMQWqjUSepVE=,iv:j7oYwAR7LKiiXsZgoZuy481qnRC1YLOcIS7zPg9bOT0=,tag:dDrFs29/d8h8pO/oBYFRpw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
