apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:IOUjwlXiIjEEUnr6XT2f9BaeQ++DQoFiNYrsOFvY/Bfapcl67OBEXg==,iv:RLlyYB5IthueIBtZYlt6Ui9r9Vo2PrM+wPhoqW3jPTs=,tag:tvKgJDkLI5BtjVclt8H+Zg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1508vrpede8x0lspk6grkr4qlc44j3jzr4ehcddawlqlt7s65spgsaaacg7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZakt5RGxURG40MTVLQXZn
            U1RHNjVZVnMvOEtVVllCSEZWTlBPektiTGowCmFyTzlaRW5QRnhKRHhqYVVWRVJ4
            TFY0dnJCamxLbitqekF3ZHJUcVBrUUEKLS0tIDNqOFo2Ry9uNWZrdFgrNjlRTmlz
            Tys0Vm5paDk1dmdpUUs0Vk0vK2FseGMKyv0ijJoyiUt9YwaqzXkIQvil9iDaukdB
            D4yOqJ6Lr0GO7A+6X/pEwT6bFUdNWOtTFpi8UJS7GZGueCtOdwKfog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-19T18:28:27Z"
    mac: ENC[AES256_GCM,data:7BEAmEM0by/wkO9XR0Khq762goJJ5AvhPagPtGNisN7UB/Ht6B4H23jVSfYPCpsbsInix8yC1vkND+r6yOFNP9vZ8HvbZ4UdoS8cRNA5XQYwA58Z5soSgNeUI4tS1MTXBr/LrBsu06a9BYc9WVw7ctpKrVrHZmHu+EHWqvNQCGA=,iv:pAjZIrZeXMLbNU7Fck4e3INFvV5oaIiWEuQOWXMc8ks=,tag:RyTT1S86sCBcVNb682k/qA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
