apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: bookworm-secrets
    namespace: media
stringData:
    #ENC[AES256_GCM,data:zBwsYWU=,iv:jw7mPbPFCwOfbv604x1+E5/141VYHctNgCj5xPOg5GM=,tag:1ZSB5MXMjEDxtXoFNsmQ6Q==,type:comment]
    #ENC[AES256_GCM,data:DsSjnIrDflBCbNQoiU+2unqMZ3X40zmcNoUC5E8WLzQAAznStnA7yw==,iv:TnN4a2QgglQIk2Tgf6RdCrlqjXHP1BWmILwzghvh+1Y=,tag:2qjwR1wjKN+MX7VqZka6PA==,type:comment]
    #ENC[AES256_GCM,data:+tcdqj3x,iv:KXlGnqncmJCWlNUimFFVbnNzZYNWiCP/VrNRX29TxeU=,tag:bvhHaFJXnCgRDnSQS+a9lg==,type:comment]
    secret.yml: ENC[AES256_GCM,data:TCqgF5bNdfGA21z5WnTJCfzOtu874+VpNaE=,iv:1Kv0MhYLFnbWIebbESFtvop5OwlltMeplgo0kO4l1CM=,tag:oZfD+TVXI1JzW+2kFZLnLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1508vrpede8x0lspk6grkr4qlc44j3jzr4ehcddawlqlt7s65spgsaaacg7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlelZ1cGVQOERLN3NRTEY3
            RS9GM3Z0VTBPbk5pMm1ES3NMMTM0M2pJM2pVCmNXYlVaLzRLM0krcmFGQ0NlWk5S
            eFlhZDFYYmZnY3RFc09FSWU2MXM0SncKLS0tIHFkbGcwZldzbytudVZNb3VyMkNS
            aU9IOVRzMUtiRzBheXppMjdDR0d3ODgK5Qp6XXVC7f8g2oCzE2lUM3v51ZpO08Iy
            XDLWwQfsuQpkYKOYnAVHwDr+l6+wbp6lGnq1BpUqQmCOP7/VnjXxcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-15T04:00:57Z"
    mac: ENC[AES256_GCM,data:jmnOb2ZswHvNyDJZYaHj6yVlIvYpU8FbFLCRDiv/1r+Mzq6T60ITrtHQpKr4XM1+Fp6KxP6xjvlYwxRbkOIW7H9QCxC+xNabT5s1TcNIsTtAo3JrFE0zus8sksS7NIbKVnEUo4r6L718UmFP+htrG05ST4HHKN6bodjxJjFGO1Q=,iv:YH9IR0qu5gTVk9CDrRxW+HLNBx+WOPRQ9wIlmk2bCRU=,tag:rzMdNajLMR3XdgD+RV0mEw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
